# Generated by Django 5.1.4 on 2025-01-06 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='albumcovers')),
                ('artist_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='musicbox.artist')),
            ],
        ),
        migrations.CreateModel(
            name='SongTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('duration', models.DurationField()),
                ('release_date', models.DateField()),
                ('audio_file', models.FileField(upload_to='songtracks')),
                ('is_single', models.BooleanField(default=False)),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='singlescover')),
                ('album_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracks_album', to='musicbox.album')),
                ('artist_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks_artist', to='musicbox.artist')),
                ('genre_objects', models.ManyToManyField(to='musicbox.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('visibility', models.CharField(choices=[('private', 'private'), ('public', 'public')], default='private', max_length=50)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='playlistcovers')),
                ('description', models.TextField(blank=True, null=True)),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('user_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
                ('songtrack_objects', models.ManyToManyField(to='musicbox.songtrack')),
            ],
        ),
        migrations.CreateModel(
            name='LikedSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_date', models.DateTimeField(auto_now_add=True)),
                ('user_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_songs', to=settings.AUTH_USER_MODEL)),
                ('songtrack_objects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicbox.songtrack')),
            ],
        ),
    ]
