# Generated by Django 5.1.4 on 2025-03-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("musicbox", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="visibility",
            field=models.CharField(
                choices=[("private", "Private"), ("public", "Public")],
                default="private",
                max_length=50,
            ),
        ),
    ]
