# Generated by Django 5.1.4 on 2025-01-06 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicbox', '0002_artist_genre_album_songtrack_playlist_likedsongs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LikedSongs',
            new_name='LikedSong',
        ),
    ]
