# Generated by Django 5.1.4 on 2025-01-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbox', '0003_rename_likedsongs_likedsong'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
