# Generated by Django 5.1.4 on 2025-01-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbox', '0004_alter_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
